//
//  Copyright © 2013-2023 PSPDFKit GmbH. All rights reserved.
//
//  THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY INTERNATIONAL COPYRIGHT LAW
//  AND MAY NOT BE RESOLD OR REDISTRIBUTED. USAGE IS BOUND TO THE PSPDFKIT LICENSE AGREEMENT.
//  UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES.
//  This notice may not be removed from this file.
//

#import <PSPDFKitUI/PSPDFPageView.h>

#import <PSPDFKitUI/PSPDFAnnotationStateManager.h>

NS_ASSUME_NONNULL_BEGIN

@interface PSPDFPageView (Scribble) <UIIndirectScribbleInteractionDelegate, PSPDFAnnotationStateManagerDelegate>
@end

NS_ASSUME_NONNULL_END
