//
//  Copyright © 2018-2023 PSPDFKit GmbH. All rights reserved.
//
//  THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY INTERNATIONAL COPYRIGHT LAW
//  AND MAY NOT BE RESOLD OR REDISTRIBUTED. USAGE IS BOUND TO THE PSPDFKIT LICENSE AGREEMENT.
//  UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES.
//  This notice may not be removed from this file.
//

#import <PSPDFKit/PSPDFWord.h>

NS_ASSUME_NONNULL_BEGIN

@interface PSPDFWord ()

/// All `PSPDFGlyph` objects.
///
/// Originally removed on iOS 7.5, macOS 2.5.
@property (nonatomic, copy) NSArray<PSPDFGlyph *> *glyphs;

@end

NS_ASSUME_NONNULL_END
