//
//  Copyright © 2012-2023 PSPDFKit GmbH. All rights reserved.
//
//  THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY INTERNATIONAL COPYRIGHT LAW
//  AND MAY NOT BE RESOLD OR REDISTRIBUTED. USAGE IS BOUND TO THE PSPDFKIT LICENSE AGREEMENT.
//  UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES.
//  This notice may not be removed from this file.
//

#if !defined(PSPDF_STATIC_BUILD)
#import <PSPDFKit/PSPDFEnvironment+Private.h>
#else
#import "PSPDFEnvironment+Private.h"
#endif

NS_ASSUME_NONNULL_BEGIN

@protocol PSPDFFileManager;

/// Returns a unique file URL at the given path.
PSPDF_EXTERN NSURL *PSPDFProvisionalFileURLAtPathWithPathExtension(NSString *customPath, NSString *_Nullable prefix, NSString *_Nullable pathExtension);

/// Returns a unique temporary file URL.
PSPDF_APP_EXPORT NSURL *PSPDFTempFileURLWithPathExtension(NSString *_Nullable prefix, NSString *_Nullable pathExtension) NS_SWIFT_NAME(TempFileURLWithPathExtension(prefix:pathExtension:));

/// Returns a unique temporary file URL with a name suitable for a copy of the original URL.
PSPDF_APP_EXPORT NSURL *PSPDFTempFileURLForCopyOfURL(NSURL *_Nullable url) NS_SWIFT_NAME(TempFileURLForCopyOfURL(_:));

/// Returns a url for <filename>.<pathExtension> pointing to the temp directory. If no filename was given, a UDID is used instead.
PSPDF_TEST_EXPORT NSURL *PSPDFTempFileURLWithName(NSString *_Nullable fileName, NSString *_Nullable pathExtension) NS_SWIFT_NAME(TempFileURLWithName(fileName:pathExtension:));

/// Resolves path parts such as "Documents", "Cache", "Library", "Bundle" or "PSBundle" to their real path.
/// If no name is found, the bundle string is always attached, unless fallbackPath is set.
/// `resolveUnknownDocumentBlock` gets called if a token is found that isn't recognized.
/// Resolvable tokens must start with a slash. (e.g. /Bundle/Samples)
/// "Bundle" resolves to the host app bundle resource path.
/// "PSBundle" can be used for paths inside the library bundle.
/// If the path is from root directory, it won't be resolved.
/// Example: "/Bundle/Samples" resolves to AppName.app/Samples on iOS
///          and AppName.app/Contents/Resources/Samples on Catalyst.
PSPDF_EXPORT NSString *PSPDFResolvePathNames(NSString *_Nullable path, NSString *_Nullable fallbackPath);
PSPDF_EXTERN BOOL PSPDFResolvePathNamesInMutableString(NSMutableString *mutableString, NSString *_Nullable fallbackPath, NSString * (^_Nullable resolveUnknownPathBlock)(NSString *unknownPath));

/// Removes the ".pdf" or a cased derivation of it from the fileName, if it exists.
PSPDF_APP_EXPORT NSString *_Nullable PSPDFStripPDFFileType(NSString *_Nullable pdfFileName);

/// Adds the ".pdf" file extension if it doesn't exist (case insensitive).
PSPDF_APP_EXPORT NSString *_Nullable PSPDFAddPDFFileType(NSString *_Nullable pdfFileName);

/// Create folders for `path` if they don't exist.
PSPDF_APP_EXPORT BOOL PSPDFCreateFoldersFromPath(id<PSPDFFileManager> fileManager, NSString *path);

/// Deletes and recreates the directory in a given path.
PSPDF_EXTERN void PSPDFResetDirectory(NSString *directory);

/// Shortens a path. (In a way, this is the reverse of PSPDFResolvePathNames)
/// `localPDFPath` is optional, should be the path of the source PDF, so we can restore relative paths.
PSPDF_EXTERN NSString *PSPDFShortPathFromPath(NSString *path, NSString *_Nullable localPDFPath);

/// Removes the application specific part of the URL (both data and app roots).
///
/// As of iOS 8 the app directory and the document directory have different root paths.
///
/// @note This is soft deprecated and should not used for new code. It’s only used for backwards compatibility.
///
/// @param path The absolute path to process.
/// @param replaceWithPlaceholders Replace the removed portion of the path with placeholders for the inverse conversion using `PSPDFAbsolutePathFromPlaceholderPath`.
PSPDF_EXTERN NSString *_Nullable PSPDFRemoveApplicationPathFromPath(NSString *_Nullable path, BOOL replaceWithPlaceholders);

/// Converts relative paths generated by `PSPDFRemoveApplicationPathFromPath` with `replaceWithPlaceholders` enabled to absolute paths.
///
/// @note This is soft deprecated and should not used for new code.
PSPDF_EXTERN NSString *_Nullable PSPDFAbsolutePathFromPlaceholderPath(NSString *_Nullable path);

/// Access the iCloud document path (function can block for a while, XPC)
PSPDF_EXTERN NSString *PSPDFiCloudMobileDocumentsPath(void);

// MARK: Path Helper

/// Fixes paths that are converted incorrectly via NSURL description instead of path.
PSPDF_EXTERN BOOL PSPDFIsIncorrectPath(NSString *path);
PSPDF_EXTERN NSString *PSPDFFixIncorrectPath(NSString *path);

/// Detect if a path is absolute (root) based.
PSPDF_TEST_EXPORT BOOL PSPDFIsRootPath(NSString *path) NS_SWIFT_NAME(isRootPath(_:));

NS_ASSUME_NONNULL_END
