//
//  Copyright © 2012-2023 PSPDFKit GmbH. All rights reserved.
//
//  THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY INTERNATIONAL COPYRIGHT LAW
//  AND MAY NOT BE RESOLD OR REDISTRIBUTED. USAGE IS BOUND TO THE PSPDFKIT LICENSE AGREEMENT.
//  UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES.
//  This notice may not be removed from this file.
//

#import <PSPDFKit/PSPDFEnvironment.h>
#import <PSPDFKit/PSPDFLocalization.h>
#import <PSPDFKit/PSPDFLocalizedStringKeys.h>
#import <PSPDFKit/PSPDFMacros+Private.h>
#import <PSPDFKit/PSPDFMacros.h>

NS_ASSUME_NONNULL_BEGIN

// To avoid passing around string literals as keys, the constants generated by UpdateLocalizedStringKeys.swift
// should be used. See that file for more information about the generation process.
 
/// Returns the (localized) name of the current app.
PSPDF_APP_EXPORT NSString *PSPDFAppName(void) NS_SWIFT_NAME(AppName());

/// Guesses the user’s name.
///
/// This returns nil on iOS 16, except on Catalyst or in Simulator debug builds.
PSPDF_SDK_EXPORT NSString *_Nullable PSPDFGuessUserName(void) NS_SWIFT_NAME(GuessedUserName());

/// Tries to extract the username from the device name (using iTunes default device naming conventions).
/// Returns nil if extraction is not possible.
PSPDF_EXTERN NSString *_Nullable PSPDFExtractUsernameFromDefaultDeviceName(NSString *deviceName)  NS_SWIFT_NAME(ExtractUsernameFromDefaultDeviceName(_:));

/// Same as `PSPDFLocalize()` but will add an ellipsis (...) at the end.
PSPDF_APP_EXPORT NSString *PSPDFLocalizeWithEllipsis(PSPDFLocalizedStringKey stringToken) NS_FORMAT_ARGUMENT(1);

/// Same as `PSPDFLocalizeFormatted()` but will add an ellipsis (...) at the end.
PSPDF_SDK_EXPORT NSString *PSPDFLocalizeWithEllipsisFormatted(PSPDFLocalizedStringKey stringToken, ...) NS_FORMAT_FUNCTION(1, 2);

/// Localizes a size in the form of `100 x 150`
PSPDF_SDK_EXPORT NSString *PSPDFLocalizeSize(CGSize size);

/// Get the preferred locale.
PSPDF_APP_EXPORT NSLocale *PSPDFPreferredLocale(void) NS_SWIFT_NAME(PreferredLocale());

/// Access the PSPDFKit.bundle.
PSPDF_TEST_EXPORT NSBundle *PSPDFKitBundle(void) NS_SWIFT_NAME(PDFKitBundle());

/// Warns if the bundle is missing.
PSPDF_SDK_EXPORT void PSPDFWarnOnceIfBundleIsMissing(void) NS_SWIFT_NAME(WarnOnceIfBundleIsMissing());

/// Returns the string argument marked as localized to avoid analyzer warnings.
/// Use this for strings that may be shown in the UI but should not be localized.
/// http://clang-analyzer.llvm.org/faq.html
__attribute__((annotate("returns_localized_nsstring"))) PSPDF_SDK_EXPORT NSString *PSPDFLocalizationNotNeeded(NSString *string) NS_SWIFT_NAME(MarkLocalized(self:));

/// Localizes strings. Will return nil if there is no entry. If the second
/// argument is `NO`, it will not try to fall back on the default (en) locale.
PSPDF_SDK_EXPORT NSString * PSPDFLocalizeWithoutFallbackUsingDefaultLocaleIfNeeded(NSString *string, BOOL fallBackToDefaultLocale);

NS_ASSUME_NONNULL_END
