//
//  Copyright © 2012-2023 PSPDFKit GmbH. All rights reserved.
//
//  THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY INTERNATIONAL COPYRIGHT LAW
//  AND MAY NOT BE RESOLD OR REDISTRIBUTED. USAGE IS BOUND TO THE PSPDFKIT LICENSE AGREEMENT.
//  UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES.
//  This notice may not be removed from this file.
//

#import <PSPDFKit/PSPDFEnvironment.h>
#import <PSPDFKit/PSPDFGlyphRange.h>

NS_ASSUME_NONNULL_BEGIN

/// Represents a single character (glyph, quad) on the PDF page.
///
/// @note Glyphs are created from the PDF contents and not meant to be created manually.
PSPDF_CLASS_SUBCLASSING_RESTRICTED_SWIFT(Glyph)
@interface PSPDFGlyph : NSObject<NSCopying, NSSecureCoding>

PSPDF_EMPTY_INIT_UNAVAILABLE

/// Frame of the glyph, normalized to take the font of the text block it is in into account.
@property (nonatomic, readonly) CGRect frame;

/// Character content (usually a single character).
@property (nonatomic, copy, readonly) NSString *content;

/// Checks if after this glyph is a newline character.
@property (nonatomic, readonly) BOOL lineBreaker;

/// Checks if glyph is a word boundary (space, parenthesis, control character).
@property (nonatomic, readonly, getter=isWordBreaker) BOOL wordBreaker;

/// Returns YES if glyph is end of a word or line.
@property (nonatomic, readonly) BOOL isWordOrLineBreaker;

/// Returns `true` if the receiver is an autogenerated filler.
@property (nonatomic, readonly, getter=isGenerated) BOOL generated;

/// Index of the glyph on the page, and in `PSPDFTextParser.glyphs`. All glyphs from the same page are guaranteed
/// to have unique values for this property.
@property (nonatomic, readonly) NSInteger indexOnPage;

@end

/// Returns the concatenated text content of an array of glyphs.
PSPDF_EXPORT NSString *PSPDFStringFromGlyphs(NSArray<PSPDFGlyph *> *_Nullable glyphs);

/// Returns the bounding box that tightly encloses all the glyphs in the given array. This will be `CGRectZero` if `glyphs` is empty.
PSPDF_EXPORT CGRect PSPDFBoundingBoxFromGlyphs(NSArray<PSPDFGlyph *> *_Nullable glyphs);

/// Returns the combined frames of the glyphs separated by lines, and (by reference) the bounding box that tightly encloses all these frames.
///
/// The return value is suitable to use as the `rects` property of a text markup annotation.
/// If all the glyphs are on the same line, then the returned array will contain a single entry that is equal to the
/// returned bounding box. If the glyphs span multiple lines, then the array will contain one rectangle for each line.
/// For example, the following 11 glyphs would return an array of 3 rectangles:
///
/// □□□■■■
///
/// ■■■■■■
///
/// ■■□□□□
///
/// Some padding should be added to the bounding box returned by reference before setting it as the
/// bounding box of a text markup annotation to ensure the rendering of the annotation is not clipped.
PSPDF_EXPORT NSArray<NSValue *> *PSPDFRectsFromGlyphs(NSArray<PSPDFGlyph *> *_Nullable glyphs, CGRect *boundingBox);

/// Returns the range of the glyphs in the text parser, assuming the glyphs are in ascending order of their `indexOnPage`.
///
/// If `glyphs` is not sorted, this will return an incorrect result.
///
/// `PSPDFInvalidGlyphRange` is returned if `glyphs` is an empty array,
/// or if the last glyph has an indexOnPage that is prior to the first glyph.
PSPDF_EXPORT NSRange PSPDFRangeFromGlyphs(NSArray<PSPDFGlyph *> *glyphs);

NS_ASSUME_NONNULL_END
